_target_: nlp.datasets.datamodule.Datamodule

data_path: /home/konradkaranowski/storage/nlp/korpus_wzorcowy.pkl
target_path: /home/konradkaranowski/storage/nlp/herbet_df.csv
embeddings_path: /home/konradkaranowski/storage/nlp/herbert/
force_reprocess: false

language_model: "allegro/herbert-base-cased"
max_length: 512
padding: true
truncation: true


embedding_dim: 768
num_classes: 12

test_size: 0.2
train_val_ratio: 0.8

batch_size: 512
